// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbrmbulcsmuucplgddnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpicm1idWxjc211dWNwbGdkZG5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MTcxNjIsImV4cCI6MjA1NjM5MzE2Mn0.RKeDrmCQY2fDJucPO-T0Mqtg3VJKTQPAE6CZbuW3wNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);